First stab at making the connectionpool focused on which host has actually been connected to
However the secondary connection blows up with
System.NullReferenceException: Object reference not set to an instance of an object.
   at Npgsql.NpgsqlConnector.Cleanup() in C:\Users\Rob\source\repos\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1416
   at Npgsql.NpgsqlConnector.Break() in C:\Users\Rob\source\repos\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1350
   at Npgsql.NpgsqlConnector.<Open>d__149.MoveNext() in C:\Users\Rob\source\repos\npgsql\src\Npgsql\NpgsqlConnector.cs:line 457
--- End of stack trace from previous location where exception was thrown ---

I think this is because I need to read/write from the NpgsqlConnector rather than wrapping into a connection